---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages And Post
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - blog-post
- type: heading
  label: Projects an Presentations
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*.md"
  new_doc_ext: md
- type: directory
  path: _presentations
  label: Presentations
  create: all
  match: "**/*"
- type: directory
  path: _wiki
  label: Wiki
  create: all
  match: "**/*"
- type: heading
  label: Stuffs
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: _include
  label: Include
  create: all
  match: "**/*"
- type: directory
  path: assets
  label: Assets
  create: all
  match: "**/*"
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll clean && bundle exec jekyll serve --drafts
    --unpublished --future --port 8080 --host 0.0.0.0 -d _site