---
label: configs
hide_body: false
fields:
- type: field_group_list
  name: configs
  label: configs
  fields:
  - type: text
    name: name
    label: name
  - name: xpto
    type: select
    default: []
    config:
      required: false
      options: []
      source:
        type: documents
        section: projects
        file: _projects/1-loucuradevaneia.md
        path: tags
    label: xpto
  description: A list of configs to use on post
pages:
- _data/style.yml.md
