---
label: configs
hide_body: true
fields:
- type: field_group_list
  name: configs
  label: configs
  fields:
  - type: text
    name: name
    label: name
  - name: xpto
    type: select
    default: []
    config:
      required: false
      options: []
      source:
        type: pages
        section: projects
        file: 
        path: 
    label: xpto
  description: A list of configs to use on post
pages:
- _data/color.yml.md
- _data/style.yml.md
