---
label: configs
hide_body: true
fields:
- type: field_group_list
  name: configs
  label: configs
  fields:
  - type: text
    name: name
    label: name
  description: A list of configs to use on post
pages:
- _data/color.yml.md
