name: Recreate forestry Branch

on:
  pull_request:
    types: [synchronize]
    
jobs:
  delete-branch:
    name: Delete forestry branch
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.FORESTRY_TOKEN }}
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.FORESTRY_TOKEN }}
        with:
          branch: 'forestry'
